# Generated by Django 3.2 on 2021-04-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grais', '0027_incidentalreport_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followup_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followup_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of follow-up'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incidental_report',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='grais.incidentalreport'),
        ),
    ]
